#!/bin/bash
#
# skripti algus
#
echo -n "Siseta kuu number: "
read kuu

if [[ $kuu -ge 1 ]] && [[ $kuu -le 2 ]] # arvestab numbrid 1-2 
then
      echo "Praegu on Talv" # valjastab vastuse (kui on 1-2 siis on talv jne)

elif [[ $kuu -ge 3 ]] && [[ $kuu -le 5 ]]
then
      echo "Praegu on kevad"

elif [[ $kuu -ge 6 ]] && [[ $kuu -le 8 ]]
then
      echo "Praegu on suvi"

elif [[ $kuu -ge 9 ]] && [[ $kuu -le 11 ]]
then
      echo "Praegu on sugis"

fi
#
# skripti lopp
