#!/bin/bash
#
# skripti algus
# 
echo -n "Sisesta aja vaartus: "
read aeg

if [[ $aeg -ge 6 ]] && [[ $aeg -le 11 ]] # hommiku aja vahe on 6-11
then
      echo "Tere hommikust"

elif [[ $aeg -ge 12 ]] && [[ $aeg -le 17 ]]
then
      echo "Tere paevast"

elif [[ $aeg -ge 18 ]] && [[ $aeg -le 21 ]]
then
      echo "Tere ohtust"

elif [[ $aeg -ge 22 ]] && [[ $aeg -le 24 ]]
then
      echo "Head ood"

elif [[ $aeg -ge 1 ]] && [[ $aeg -le 5 ]] # 2 head ood kuna 22-5 ei ole voimalik
then
      echo "Head ood"

fi
#
# skripti lopp
