#!/bin/bash
#
# Sistetatud arvude summa
#
echo -n "Sisesta suvaline taisarv: "
read arv

summa=0

while [ $arv -ne 0 ]
do

      jaak=$(( $arv % 10 )) # jagamine 10-ga
      summa=$(( $summa + $jaak )) # jaagi ja summa liitmine
      arv=$(( $arv / 10 )) 

done

echo "$summa"

# skripti lopp

