#!/bin/bash
#
echo -n "Sisesta oma ees- ja perenimi:" # valjastab jutumarkides kirjutatud teksti
read eesnimi perenimi # laseb kirjutada midagi , mis on seotud jutumargi sisuga
echo "Sinu eesnimi on $eesnimi ja perenimi on $perenimi" # valjastab sisestatud nimed
echo  "Tere, $eesnimi $perenimi" # valjastab antud sisu sinu sisestatud nimega
