#!/bin/bash
#
# tordi andmed
#
echo "Sisesta kandiku pikkus (cm)"
read pikkus

echo "Sisesta kandiku laius (cm)"
read laius

echo "Sisesta kupsise suurus (cm)"
read ky_suurus

echo "Sisesta kupsise laius (cm)"
read ky_laius

echo "Sisesta kupsise arv pakis"
read kogus

echo "Sisesta kupsise paki arv"
read mitu

echo "Sisesta tordi kihtide arv"
read k_arv
#
# Kandiku pindala
pindala=`expr $pikkus \* $laius` # arvutab antud koguse
# Kupsiste arv
kkogus=`expr $kogus \* $mitu`
# Kupsise kindala
ky_pindala=`expr $ky_suurus \* $ky_laius`
echo "Kandiku pindala on $pindala, Kypsise pindala on $ky_pindala ja kupsiste arv on $kkogus" # valjastab otsitud tulemused 

